# Site settings
title: Bleep Systems
email: neil@bleepsystems.com
description: > # this means to ignore newlines until "baseurl:"
  Internet Systems.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bleepsystems.github.io" # the base hostname & protocol for your site
github_username:  nhc

# Build settings
markdown: kramdown
